matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04 SWIFT_SNAPSHOT=4.0-DEVELOPMENT-SNAPSHOT-2017-06-29-a
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.0-DEVELOPMENT-SNAPSHOT-2017-06-29-a
    - os: osx
      osx_image: xcode9
      sudo: required
      env: SWIFT_SNAPSHOT=4.0-DEVELOPMENT-SNAPSHOT-2017-06-29-a

script:
  - ./build.sh
